export const USER_SIGNUP_PROFESSIONAL = 'submit_signUp_professional';
export const GET_ANNOUNCEMENTS = 'gets_list_anouncemments';
export const GET_JOB_CATEGORIES = 'gets_list_categories';
export const GET_JOB_CATEGORIES_LOADING = 'loading_job_categories';
export const GET_USER_REVIEWS = 'gets_reviews_from_user';
export const GET_USER_ANNOUNCEMENTS = 'gets_announcements_from_user';
export const GET_ANNOUNCEMENTS_BY_JOB = 'gets_announcements_by_job';
export const GET_PROFESSIONAL = 'gets_professional';
export const GET_PROFESSIONALS = 'gets_professionals';
export const GET_CLIENT = 'gets_client';
export const USER_LOGIN_SUCCESS = 'logins_user';
export const UPDATE_PROFESSIONAL = 'updates_professional_instance';
export const UPDATE_ANNOUNCEMENTS = 'updates_announcement_instance';
export const UPDATE_CLIENT = 'updates_client_instance';
export const SIGNUP_SUCCESS = 'signups_user_instance';
export const SIGNUP_ERROR = 'error_on_user_signup';
export const SIGNUP_LOADING = 'requesting_user_signup';
export const USER_LOGIN_ERROR = 'login_error';
export const GET_PROFESSIONAL_BY_USERNAME = 'gets_professional_with_username_as_query';
export const GET_CLIENT_BY_USERNAME = 'gets_client_with_username_as_query';
export const PUT_SERVICE_LOADING = 'loading_creates_service_instance';
export const PUT_SERVICE_ERROR = 'error on creates_service_instance';
export const PUT_SERVICE_SUCCESS = 'creates_service_instance';
export const PUT_REVIEW = 'creates_review_instance';
export const GET_REVIEWS = 'gets_all_reviews';
export const GET_CLIENT_SERVICES = 'get_client_related_services';
export const POST_REVIEW_SUCCESS = 'posts_review success';
export const POST_REVIEW_LOADING = ' post review loading'
export const POST_REVIEW_ERROR = ' post review error'
export const POST_ANNOUNCEMENT_SUCCESS = 'posts_announcement_success';
export const POST_ANNOUNCEMENT_ERROR = 'posts_announcement_error';
export const POST_ANNOUNCEMENT_LOADING = 'posts_announcement_loading';
export const GET_JOB_SUB_CATEGORIES = 'gets_lists_job_sub_categories';
export const USER_LOGIN_LOADING = 'login_loading';
export const GET_CLIENT_REVIEWS = 'client reviews'
export const UPDATE_ANNOUNCEMENTS_SUCCESS = 'updates annoucements success';
export const UPDATE_ANNOUNCEMENTS_ERROR = 'error when updating announemnt';
export const UPDATE_ANNOUNCEMENTS_LOADING = 'requesting update on announcement';
export const UPDATE_PROFESSIONAL_SUCCESS = 'success on updating professional';
export const UPDATE_PROFESSIONAL_ERROR = 'error on updating professional';
export const UPDATE_PROFESSIONAL_LOADING = 'loading update professional';
export const UPDATE_CLIENT_LOADING = 'loading update client';
export const UPDATE_CLIENT_SUCCESS = 'success on updating client';
export const UPDATE_CLIENT_ERROR = 'error on updating client';
export const GET_USER_ANNOUNCEMENTS_LOADING = 'user loading announcements';
export const GET_USER_ANNOUNCEMENTS_SUCCESS = 'user success announcements';
export const GET_USER_ANNOUNCEMENTS_ERROR = 'user error announcements';
export const GET_ANNOUNCEMENTS_LOADING = ' announcemnts loading';
export const GET_ANNOUNCEMENTS_SUCCESS = 'announcements success';
export const GET_ANNOUNCEMENTS_ERROR = 'announcements error';
export const GET_JOB_BY_NAME_SUCCESS = ' success get job by name';
export const GET_JOB_BY_NAME_ERROR = ' error get job by name';
export const GET_JOB_BY_NAME_LOADING = ' loading get job by name';
export const GET_ANNOUNCEMENT_REVIEWS_SUCCESS = 'get announcement reviews success'
export const GET_ANNOUNCEMENT_REVIEWS_ERROR = 'get announcement reviews error'
export const GET_ANNOUNCEMENT_REVIEWS_LOADING = 'get anouncement reviews loading'
export const REQUEST_SEARCH = 'request search'
export const UPDATE_SEARCH_PARAMS = 'update search params'
export const STOP_SEARCH_REQUEST = 'stops requesting search'
export const GET_REVIEWS_ERROR = 'error getting reviews'
export const GET_REVIEWS_LOADING = 'loading reviews'
export const GET_REVIEWS_SUCCESS = 'success getting reviews'
export const UPDATE_SERVICE_SUCCESS = 'updates service success';
export const UPDATE_SERVICE_ERROR = 'error when updating service';
export const UPDATE_SERVICE_LOADING = 'requesting update on service';
export const GET_SERVICES_LOADING = ' SERVICES loading';
export const GET_SERVICES_SUCCESS = 'SERVICES success';
export const GET_SERVICES_ERROR = 'SERVICES error';
export const UPDATE_REVIEW_ERROR = 'UPDATE_REVIEW_ERROR'
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS'
export const UPDATE_REVIEW_LOADING = 'UPDATE_REVIEW_LOADING'
export const GET_USER_ID = 'GET_USER_ID'
export const GET_USER_NAME = 'GET_USER_NAME'
export const GET_USER_LASTNAME = 'GET_USER_LASTNAME'
export const GET_USER_FULLNAME = 'GET_USER_FULLNAME'
export const GET_USER_URL = 'GET_USER_URL'
export const GET_USER_TYPE = 'GET_USER_TYPE'
export const SET_USER_DATA = 'SET_USER_DATA'
export const LOAD_USER_FROM_COOKIES = 'LOAD_USER_FROM_COOKIES'
export const USER_LOGOUT = 'USER_LOGOUT'
export const RESET_SEARCH_PARAMS = 'RESET_SEARCH_PARAMS'
export const GET_PROFILE_BY_USERNAME = 'GET_PROFILE_BY_USERNAME'
